# Сolor palette: https://stephango.com/flexoki
# ---
# black       "#100F0F" bg
# base-950    "#1C1B1A" bg-2
# base-900    "#282726" ui
# base-850    "#343331" ui-2
# base-800    "#403E3C" ui-3
# base-700    "#575653" tx-3
# base-500    "#878580" tx-2
# base-200    "#CECDC3" tx
# red-400     "#D14D41" re
# orange-400  "#DA702C" or
# yellow-400  "#D0A215" ye
# yellow-600  "#AD8301" ye-2
# green-400   "#879A39" gr
# cyan-400    "#3AA99F" cy
# cyan-600    "#24837B" cy-2
# cyan-700    "#1C6C66" cy-700
# cyan-900    "#122F2C" cy-900
# blue-400    "#4385BE" bl
# purple-400  "#8B7EC8" pu
# magenta-400 "#CE5D97" ma

[app]
overall = { bg = "#100F0F" } # bg

[mgr]
cwd = { fg = "#CECDC3", bold = true } # tx

# Find
find_keyword = { fg = "#3AA99F", reversed = true } # cy
find_position = { fg = "#3AA99F", bold = true, italic = true } # cy

# Marker
marker_copied = { fg = "#879A39", bg = "#879A39" } # gr, gr
marker_cut = { fg = "#D14D41", bg = "#D14D41" } # re, re
marker_marked = { fg = "#1C6C66", bg = "#1C6C66" } # cy-700, cy-700
marker_selected = { fg = "#3AA99F", bg = "#3AA99F" } # cy, cy

# Count
count_copied = { fg = "#879A39", bold = true, reversed = true } # gr
count_cut = { fg = "#D14D41", bold = true, reversed = true } # re
count_selected = { fg = "#3AA99F", bold = true, reversed = true } # cy

# Border
border_symbol = "│"
border_style = { fg = "#282726" } # ui

[indicator]
parent = { underline = true }
current = { fg = "#CECDC3", bg = "#282726" } # tx, ui
preview = { underline = true }
padding = { open = "█", close = "█" }

[tabs]
active = { fg = "#CECDC3", bg = "#403E3C", bold = true } # tx, ui-3
inactive = { fg = "#878580", bg = "#282726" } # tx-2, ui
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
# Normal mode
normal_main = { fg = "#CECDC3", bg = "#403E3C", bold = true } # tx, ui-3
normal_alt = { fg = "#878580", bg = "#282726" } # tx-2, ui

# Select mode
select_main = { fg = "#100F0F", bg = "#3AA99F", bold = true } # bg, cy
select_alt = { fg = "#3AA99F", bg = "#122F2C" } # cy, cy-900

# Unset mode
unset_main = { fg = "#100F0F", bg = "#3AA99F", bold = true } # bg, cy
unset_alt = { fg = "#3AA99F", bg = "#122F2C" } # cy, cy-900

[status]
overall = { fg = "#CECDC3" } # tx

# Permissions
perm_type = { fg = "#4385BE" } # bl
perm_read = { fg = "#D0A215" } # ye
perm_write = { fg = "#D14D41" } # re
perm_exec = { fg = "#879A39" } # gr
perm_sep = { fg = "#878580" } # tx-2

# Progress
progress_label = { fg = "#100F0F" } # bg
progress_normal = { fg = "#3AA99F", bg = "#1C6C66" } # cy, cy-700
progress_error = { bg = "#D14D41" } # re

[which]
cols = 3
mask = { bg = "#1C1B1A" } # bg-2
cand = { fg = "#3AA99F", bold = true } # cy
rest = { fg = "#3AA99F", italic = true } # cy
desc = { fg = "#575653" } # tx-3
separator = " "
separator_style = { }

[confirm]
border = { fg = "#403E3C" } # ui-3
title = { fg = "#575653", bold = true } # tx-3
body = { fg = "#CECDC3", bold = true } # tx
list = { fg = "#CECDC3" } # tx
btn_yes = { fg = "#CECDC3", bg = "#403E3C", bold = true } # tx, ui-3
btn_no = { fg = "#878580", bg = "#282726" } # tx-2, ui

[spot]
border = { fg = "#403E3C" } # ui-3
title = { fg = "#575653", bold = true } # tx-3
tbl_col = { fg = "#878580" } # tx-2
tbl_cell = { fg = "#CECDC3", bg = "#282726" } # tx, ui

[notify]
# Notification title
title_info = { fg = "#4385BE" } # bl
title_warn = { fg = "#DA702C" } # or
title_error = { fg = "#D14D41" } # re

[pick]
border = { fg = "#403E3C", bold = true } # ui-3
active = { fg = "#CECDC3" } # tx
inactive = { fg = "#878580" } # tx-2

[input]
border = { fg = "#403E3C" } # ui-3
title = { fg = "#575653", bold = true } # tx-3
value = { fg = "#CECDC3" } # tx
selected = { bg = "#1C1B1A" } # bg-2

[cmp]
border = { fg = "#403E3C", bold = true } # ui-3
active = { fg = "#CECDC3", bg = "#282726" } # tx, ui
inactive = { fg = "#878580" } # tx-2

[tasks]
border = { fg = "#403E3C" } # ui-3
title = { fg = "#575653", bold = true } # tx-3
hovered = { fg = "#CECDC3", bg = "#282726" } # tx, ui

[help]
on = { fg = "#4385BE" } # bl
run = { fg = "#3AA99F" } # cy
desc = { fg = "#575653", italic = true } # tx-3
hovered = { bg = "#282726" } # ui
footer = { fg = "#100F0F", bg = "#3AA99F", bold = true } # bg, cy

[filetype]
rules = [
  # Empty files
  { mime = "inode/empty", fg = "#575653" }, # tx-3

  # Special files
  { url = "*", is = "orphan", fg = "#575653" }, # tx-3
  { url = "*/", is = "orphan", fg = "#575653" }, # tx-3
  { url = "*", is = "link", fg = "#3AA99F" }, # cy
  { url = "*/", is = "link", fg = "#3AA99F" }, # cy
  { url = "*", is = "block", fg = "#CECDC3" }, # tx
  { url = "*", is = "char", fg = "#CECDC3" }, # tx
  { url = "*", is = "fifo", fg = "#CE5D97" }, # ma
  { url = "*", is = "sock", fg = "#CE5D97" }, # ma
  { url = "*", is = "sticky", fg = "#CECDC3" }, # tx
  { url = "*", is = "dummy", fg = "#575653" }, # tx-3

  # Fallback
  { url = "*/", fg = "#CECDC3" }, # tx
  { url = "*", is = "exec", fg = "#879A39" }, # gr
  { url = "*", fg = "#878580" } # tx-2
]

[icon]
dirs = [
  { name = ".config", text = "", fg = "#3AA99F" }, # cy
  { name = ".git", text = "", fg = "#3AA99F" }, # cy
  { name = ".github", text = "", fg = "#3AA99F" }, # cy
  { name = ".npm", text = "", fg = "#3AA99F" }, # cy
  { name = "Desktop", text = "", fg = "#3AA99F" }, # cy
  { name = "Development", text = "", fg = "#3AA99F" }, # cy
  { name = "Documents", text = "", fg = "#3AA99F" }, # cy
  { name = "Downloads", text = "", fg = "#3AA99F" }, # cy
  { name = "Library", text = "", fg = "#3AA99F" }, # cy
  { name = "Movies", text = "", fg = "#3AA99F" }, # cy
  { name = "Music", text = "", fg = "#3AA99F" }, # cy
  { name = "Pictures", text = "", fg = "#3AA99F" }, # cy
  { name = "Public", text = "", fg = "#3AA99F" }, # cy
  { name = "Videos", text = "", fg = "#3AA99F" } # cy
]
conds = [
  # Special files
  { if = "orphan", text = "", fg = "#575653" }, # tx-3
  { if = "link", text = "", fg = "#3AA99F" }, # cy
  { if = "block", text = "", fg = "#CECDC3" }, # tx
  { if = "char", text = "", fg = "#CECDC3" }, # tx
  { if = "fifo", text = "", fg = "#CE5D97" }, # ma
  { if = "sock", text = "", fg = "#CE5D97" }, # ma
  { if = "sticky", text = "", fg = "#CECDC3" }, # tx
  { if = "dummy", text = "", fg = "#575653" }, # tx-3

  # Fallback
  { if = "dir", text = "", fg = "#3AA99F" }, # cy
  { if = "exec", text = "", fg = "#879A39" }, # gr
  { if = "!dir", text = "", fg = "#878580" } # tx-2
]